#!/usr/bin/env bash
set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)
cd "$SCRIPT_DIR"
VENV_DIR="$SCRIPT_DIR/venv"
VENV_PYTHON="$VENV_DIR/bin/python"


if [ ! -d "$VENV_DIR" ]; then
  echo "Creating virtual environment..."
  python -m venv "$VENV_DIR"
fi

if ! command -v pdm  &> /dev/null; then
  echo "Installing pdm..."
  pip install --user pdm
fi

if [ ! -f "$VENV_DIR/bin/ruff" ]; then # just checking if any dependency has been installed
  echo "Installing dependencies..."
  pdm install
fi


exec pdm run "dev" "$@"
