#!/usr/bin/env bash
set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)
cd "$SCRIPT_DIR"
VENV_DIR="$SCRIPT_DIR/venv"
VENV_PYTHON="$VENV_DIR/bin/python"

if ! command -v pdm  &> /dev/null; then
  echo "Installing pdm..."
  $VENV_DIR/bin/pip install pdm

fi

pdm install

exec pdm run "dev" "$@"
